### ISSUE TITLE
Add support for IE

### ISSUE THREAD

**Issue by juanchavezlive** [pioug/angular-whimsical-ripple#1]
Hi Pal, First of all congratulations for your directive, i have tested it and is the best among the others.

The only bad point is that in IE 11 (and i guess below) i get the next error:

![1](https://cloud.githubusercontent.com/assets/5005394/7620712/4fecb1c8-f987-11e4-9fd6-fcd10c416e1d.png)

I was wondering if you have in mind add support for IE :)

**Comment by pioug** [comment]
Better late than never :sweat_smile: Just merged this https://github.com/pioug/angular-whimsical-ripple/pull/2. It should be fine now for IE

**Comment by juanchavezlive** [comment]
Great !!  I will take a look on it :) :) :) :+1:
